version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # MongoDB
      MONGO_URI: ${MONGO_URI}
      # KKBOX
      KK_ID: ${KK_ID}
      KK_SECRET: ${KK_SECRET}
      # Spotify
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      # Firebase
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTHDOMAIN: ${FIREBASE_AUTHDOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_APPID: ${FIREBASE_APPID}
      ADMIN_UID: ${ADMIN_UID}
      # Port setting
      PORT: ${PORT}
    ports:
      - "80:80"
